фильтры
htmlacademy-javascript/808541-keksobooking-24 pull request #11
Opened 2021-11-02 11:48 UTC by MakaevaElena

2021-11-03 06:54 UTC, 4err requested changes

2021-11-03 06:54 UTC, 4err commented on js/api.js
> +const getData = (onSuccess, onFail, callback) => {
` callback` тут явно лишний. Все обрабатываем через onSuccess или onFail

2021-11-03 06:54 UTC, 4err commented on js/filter.js
> +    element.addEventListener('click', debounce(updateFilter(filterFeatures), DELAY)));
При зименении любого параметра у нас пересчитываются все параметры сразу, так что у нас вся фильтрация должна проходить по всем пунктам сразу, иначе получится, что я выбрал 2 гостя, список отфильтровался, затем выбираю цену, а список то уже и забыл про 2 гостя и вывел всех но подходящих под цену

2021-11-07 10:53 UTC, 4err requested changes
Все неиспользуемые функции и временные вызовы нужно удалить. Если они не используются в проекте, то они больше не нужны. 

Все циклы for, которые перебирают полностью массив нужно переделать в forEach

А где используется троттл?

2021-11-07 10:53 UTC, 4err commented on js/filter.js
> +      if (featureList.length > 0) {
Вот эти 2 условия можно объединить в одно

2021-11-07 10:53 UTC, 4err commented on js/form.js
> +const MIN_GUESTS = '0';
Все константы должны быть описаны до основного кода.

2021-11-07 10:53 UTC, 4err commented on js/main.js
> +map.on('load', toDefaultMap());
2 проблемы. 
1. Нужно передавать обработчик `toDefaultMap`, а не вызов обработчика `toDefaultMap()`. Странно, что оно работает корректно :) 
2. Все обработчики, которые передаются должны иметь либо префикс `on` либо постфикс `handler`
Проверь остальные обработчики также.

2021-11-07 13:16 UTC, MakaevaElena commented on js/main.js
> +map.on('load', toDefaultMap());
1. - toDefaultMap() без скобок не работает.
не понимаю почему.

2021-11-08 09:54 UTC, merged