подключен скрипт. Функция случайного числа, функция округления дробно…
htmlacademy-javascript/808541-keksobooking-24 pull request #2
Opened 2021-09-25 11:59 UTC by MakaevaElena

…й части.

2021-09-25 16:56 UTC, 4err requested changes
https://take.ms/tShzz - почему-то `false` не возвращает, хотя я явно указываю некорректные данные
Со второй функцией такая же проблема.

2021-09-25 16:56 UTC, 4err commented on index.html
> +<script scr="js/main.js"></script>
`src`

2021-09-25 16:56 UTC, 4err commented on js/main.js
> +getRandomIntInclusive(); // Временный вызов функции
Для корректного вызова нужно и параметры передать.

2021-09-26 12:18 UTC, MakaevaElena commented on index.html
> +<script scr="js/main.js"></script>
исправила на src

2021-09-26 12:18 UTC, MakaevaElena commented on js/main.js
> +getRandomIntInclusive(); // Временный вызов функции
параметры передала

2021-09-26 12:20 UTC, MakaevaElena commented on index.html
> +<script scr="js/main.js"></script>
в функциях поменяла && на ||, 
работает.

2021-09-26 13:30 UTC, merged